### ISSUE TITLE
Why not using Zipline as backtested and trading Algo

### ISSUE THREAD

**Issue by carstenf** [9600dev/mmr#2]
Hi

why not using Zipline (or Zipline-reloded) as a backtested and trading engine? (there are several books for introduction )
There are several ad on, for example for fundamental data -> see https://github.com/pbharrin/alpha-compiler
As well there is already a connection to IB and alpaca -> Zipline Trader
There was as well a comment for someone who had integrated option data
What's missing is a good connection to different data provider...
And everything is a bit all over GitHub and not integrated and maintained in one place...

**Comment by 9600dev** [comment]
A decided to build myself for a few reasons: 

* I have a view that trading infrastructure and the programming model that expresses your trading algo should be tightly coupled. 
* I want to express two extra and uncommon "programming models" throughout the infra/algo libraries: [probabilistic programming](https://www.cs.cornell.edu/courses/cs4110/2016fa/lectures/lecture33.html), and [hyperparameter optimization](https://en.wikipedia.org/wiki/Hyperparameter_optimization). 
* Backtesting is obviously important for algo development, but results from those libraries often don't match real-world. I think there's a algo backtesting+backtesting trading infrastructure coupling that might help better predict real world performance. 
* I want my platform tightly coupled to a particular broker, and express that broker weirdness through the infra. There's literally hundreds of possible errors on IB, and while an algo probably shouldn't know about them, the infra certainly should. 

Hope that helps.
